### ISSUE TITLE
Sensors functionality

### ISSUE THREAD

**Issue by baristomas** [JH-Soft-Technology/InelsForHass#10]
Hello. First of all GOOD JOB you have done with Inels integration. I would like to ask if you plan to integrate also thermometers from light switches? Not sure if this functionality is not and will never be available or just on your to- do list. Many thanks for your feedback.

**Comment by jhoralek** [comment]
Hi there.

Yes I'm planing this, but I'm a bit short of time due to small kids. 
Nevertheless winter is comming and nights are going to be longer, so planty time to develop something 🤓
