### ISSUE TITLE
Fix: Error 500 showing up when setting up

### ISSUE THREAD

**Issue by Danek309044** [JH-Soft-Technology/InelsForHass#12]
## This is the error that i got when setting up: 
![image](https://github.com/JH-Soft-Technology/InelsForHass/assets/90469284/990e9d4b-c21c-48ca-9501-94aaebcb2791)
## And i did this to fix it:
- I pasted this in my SSH session with Home Assistant:
`apk add python3 && python3 -m ensurepip --default-pip && pip3 install pyinels==0.6.11 && nano /config/custom_components/inels/manifest.json`

- Then in the `manifest.json` file, I changed `“pyinels==0.6.12”` to `“pyinels==0.6.11”` and saved the file by clicking: `ctrl + x` , then `y` and after it `enter`

*This fixed my issue with the setup pop up*
## Issue:
- The issue is maybe beacuse pyinels 0.6.12 was released yesterday, so it's not updated in pip yet

**Comment by Danek309044** [comment]
Also forgot to mention that after editing the `manifest.json` you will maybe need to restart Home Assistant

**Comment by ds141414** [comment]
Facing the same issue.  Updated Home Assistant to 2023.7.2 and restarted HA and the issue is still the same.

Thanks

**Comment by jhoralek** [comment]
Sorry guys,

issue raised due to the missing publication of 0.6.12 pyinels lib. version on pypi.org.
Forgot that publication pipeline is not in github but in devops repository.

All of this because filtering unknow devices.

Sorted out now.

Have a nice day 🤓
