### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by hogyinan** [JH-Soft-Technology/InelsForHass#4]
## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by hogyinan** [comment]
where can I find some  information about the 1st coniguration in Home Assistant. What have to write in "host", "port", "version"?

**Comment by jhoralek** [comment]
- Yeah, is quit spartan version right now. 
- Basically it is communicate not with PLC unit directly, but over the connection server. It's RPi box where all your devices and entities are exported. So If you dont have a connection server, then you can not use this integration.
- Host is a url of the connection server. Basically some ip addres in your private network. For example http://192.168.1.100
- Port is 8001 as default value of the xml-rpc listener on connection server. I think, this port is not changeable.
- Version is version of PLC unit. Latest is CU3. This integration is developing against this version, so any older versions is not tested.
