### ISSUE TITLE
I can't connect

### ISSUE THREAD

**Issue by kakaduk** [JH-Soft-Technology/InelsForHass#5]
I'm trying to connect.
It spins for 5 seconds, then the error comes out: "Unexpected error"
![2022-08-26_11-05-06](https://user-images.githubusercontent.com/40637807/186834375-43ac664d-3fd3-4b8f-8230-941598493e9a.png)

**Comment by jhoralek** [comment]
Hi, host must be without http. Only IP address.
And, I'm not sure about the service port too.
Common port for inels connection server is 8001.

Kind regards

**Comment by tlleite** [comment]
Hi,
Hope you can help me,
I am getting immediatly "Unexpected error"

I am on:
Home Assistant 2022.11.3
Supervisor 2022.10.2
Operating System 9.3
Interface: 20221108.0 - latest

I have a CU3-01M Protocol version: 00.02.00
and connection server "ver. connection-server-3.367"

i'm assuming connection servers ip address, port 8001, and CU3-01M for central unit name.

![error](https://user-images.githubusercontent.com/83464719/202923572-d60c02c3-1dfe-42d1-b981-a41dbf3df649.jpg)

It would be great to get this working,

BR,
TLL

**Comment by jhoralek** [comment]
Hi ,
thanks for your post.

Please provide full log here.

JH,

**Comment by tlleite** [comment]
Here it goes:

"
Logger: custom_components.inels.config_flow
Source: custom_components/inels/config_flow.py:49
Integration: Inels ([documentation](https://github.com/JH-Soft-Technology/InelsForHass))
First occurred: 14:57:22 (1 occurrences)
Last logged: 14:57:22

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/__init__.py", line 69, in __conn
    con = ServerProxy(self.__host + ":" + str(self.__port))
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1432, in __init__
    raise OSError("unsupported XML-RPC protocol")
OSError: unsupported XML-RPC protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/inels/config_flow.py", line 75, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/inels/config_flow.py", line 49, in validate_input
    ping = await hass.async_add_executor_job(api.ping)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/__init__.py", line 79, in ping
    return self.proxy.ping()
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/__init__.py", line 51, in proxy
    self.__proxy = self.__conn()
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/__init__.py", line 74, in __conn
    raise ApiException(
pyinels.exception.ApiException: ('common_exception', 'Exception occur', OSError('unsupported XML-RPC protocol'))
"

**Comment by peterbacil** [comment]
Do i need connection server? I have CU3-02M and cannot to connect.

**Comment by jhoralek** [comment]
> Do i need connection server? I have CU3-02M and cannot to connect.

Hi Peter,

definitely you need a connection server. 

This integration is based on XML-RPC protocol, which is provided by connection server.

Kind regards

J.H.

**Comment by peterbacil** [comment]
> 

Hi, thank for your answer. Where can i download connection server?
And one more question: Is it possible to control Inels system bits via InelsForHass? Is possible to control SA2-04M connected to CU3-02M via MI3-02M via InelsForHass? 
Thank you

**Comment by jhoralek** [comment]
> > 
> 
> Hi, thank for your answer. Where can i download connection server?
> And one more question: Is it possible to control Inels system bits via InelsForHass? Is possible to control SA2-04M connected to CU3-02M via MI3-02M via InelsForHass? 
> Thank you

InelsForHass comunicate only over XML-RPC protocol, so there is no other way to control iNELS Bus, then with connection server. 
You can't download it. You need to buy it. Even if you will get just software of connection server, then you need to emulate it. For example as a container in docker ecosystem. 

I tried it couple years ago with no success.

 There is necessary to have license key which is generated based on physical network interface and software version I guess.

**Comment by peterbacil** [comment]
Thank for your answer, i will buy connection server, but i neet to know, if is possible control inels 2 actors connected to inels3 CU in InelsForHass. For example SA2-04M connected to CU3-02M via MI3-02M

thank you

**Comment by jhoralek** [comment]
> Thank for your answer, i will buy connection server, but i neet to know, if is possible control inels 2 actors connected to inels3 CU in InelsForHass. For example SA2-04M connected to CU3-02M via MI3-02M
> 
> thank you

CU unit comunicate with connection server and connection server comunicate with InelsForHass.

So when SA2-04M will appears in connection server then InelsForHass will find them.

Of course, there can be some sort of difference with naming, but it can be solved individually.

I'm still developing this integration in my free time. 

In very close future, I'm going go to refactor it because of collision with official iNELS integration which is now developing in cooperation with Elko a.s.

Kind regards

J.H.
