### ISSUE TITLE
Intergration Stops working After upgrade to HA 2023.5

### ISSUE THREAD

**Issue by ds141414** [JH-Soft-Technology/InelsForHass#7]
Hello after upgrading Home Assistant to the latest version 2023.5 the integration does not load properly and it gives out the following error

AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms

It starts on line 55 of _init_.py file.

Taken from a comment from the Home Assistant forums

**The async_setup_platforms function had been marked deprecated a while back, initially set to fail as obsolete in 2023.3. Now it actually fails in 2023.5, as previously announced.
Since all the messages in this thread are about custom integrations (likely from HACS) the developer of those custom integrations will need to update their integration to use to use await async_forward_entry_setups instead of async_setup_platforms.**

I changed

    hass.config_entries.**async_setup_platforms**(entry, PLATFORMS)

to    

    hass.config_entries.**async_forward_entry_setups**(entry, PLATFORMS)

the integration seems to load but the entities do not appear as function.

I am not a Python expert so I do not know what else that function affects.

If anyone could help it would greatly appreciated.

**Comment by jhoralek** [comment]
Hi, I know about it and it was the same issue at my instance of HA as well... I'm going to repair it asap...
