### ISSUE TITLE
iNelsForHass is not working on HA version 2023.5

### ISSUE THREAD

**Issue by adam-kosik** [JH-Soft-Technology/InelsForHass#9]
Hi Jirka,
your integration of INELS isn't loaded properly after Home Assistant update to 2023.5 version.
I can prove that everything works flawlessly under HA 2023.4.

![image](https://user-images.githubusercontent.com/75278121/236458069-05877e30-32d0-45d8-a33f-bbc437d1a11b.jpeg)

**Comment by jhoralek** [comment]
Hi Adam,

I already made fix for this issue early this morning.

Try it and give me a feedback, please.

Kind regards

JH

Dne pá 5. 5. 2023 14:31 uživatel Adam Košík ***@***.***>
napsal:

**Comment by adam-kosik** [comment]
Yeah, after fix update everything works like a charm.
Great work Jitka.

Thank you.
